version: '3.8'
services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: app
    volumes:
      - ./src:/impi-photo/src
    ports:
      - "8000:8000"
    command:
      uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
  db:
    image: postgres:13.8
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  smtp:
    image: inbucket/inbucket
    ports:
      - "9000:9000"